# -*- coding: utf-8 -*-
"""Теория алгоритмов_20

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNLVVDK0cAOPYSLlIIdQFoRXg95SewNM
"""

def optimal_triathlon_order(participants):
    # Группируем по правилу Джонсона
    group1 = []  # бас <= бег
    group2 = []  # бас > бег

    for p in participants:
        name, swim, bike, run = p
        if swim <= run:
            group1.append(p)
        else:
            group2.append(p)

    # Сортируем по возрастанию времени плавания
    group1.sort(key=lambda x: x[1])

    # Сортируем по убыванию времени бега
    group2.sort(key=lambda x: x[3], reverse=True)

    # Оптимальный порядок
    optimal_order = group1 + group2

    return optimal_order


def calculate_finishing_time(order):
    current_swim_end = 0
    max_completion_time = 0

    for name, swim, bike, run in order:
        # Время начала плавания
        swim_start = current_swim_end
        swim_end = swim_start + swim

        # Время начала велосипеда (сразу после плавания)
        bike_start = swim_end
        bike_end = bike_start + bike

        # Время начала бега (сразу после велосипеда)
        run_start = bike_end
        run_end = run_start + run

        # Обновляем время окончания плавания для следующего участника
        current_swim_end = swim_end

        # Отслеживаем максимальное время завершения
        max_completion_time = max(max_completion_time, run_end)

    return max_completion_time


def solve_triathlon(participants):
    if not participants:
        return [], 0

    # Находим оптимальный порядок
    optimal_order = optimal_triathlon_order(participants)

    # Вычисляем время завершения
    finishing_time = calculate_finishing_time(optimal_order)

    print("Оптимальный порядок участников:")
    for i, (name, swim, bike, run) in enumerate(optimal_order, 1):
        print(f"{i}. {name}: плавание = {swim} мин, велосипед = {bike} мин, бег = {run} мин")

    print(f"\nМинимальное время завершения: {finishing_time} минут")

participants = [
        ("Анна", 20, 30, 15),
        ("Михаил", 25, 35, 20),
        ("Виктор", 15, 25, 25),
        ("Мария", 30, 20, 18),
        ("Дмитрий", 22, 28, 22)
        ]

solve_triathlon(participants)